"""Shared first-run setup logic.

Writes `config/accounts.yaml` and `config/watchlist.yaml` from a few simple
inputs. Used by both the CLI (`firm init`) and the MCP tool (`init_portfolio`)
so the new-user flow can run either at the shell or directly inside Claude
Code chat without duplicating logic.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path

import yaml

DEFAULT_TICKERS = ["SPY", "QQQ", "AAPL", "MSFT", "AMD", "NVDA", "F", "INTC"]

SECTOR_HINTS = {
    "SPY": "broad_etf", "QQQ": "broad_etf", "IWM": "broad_etf",
    "AAPL": "large_cap_tech", "MSFT": "large_cap_tech",
    "GOOGL": "large_cap_tech", "AMZN": "large_cap_tech",
    "AMD": "semis_gpu", "NVDA": "semis_gpu", "INTC": "semis_gpu",
    "F": "autos", "GM": "autos",
    "IONQ": "quantum", "QBTS": "quantum", "RGTI": "quantum",
    "ACHR": "evtol",
}


def build_accounts_data(
    cash_capital: float, cash_margin: bool,
    has_ira: bool, ira_capital: float,
) -> dict:
    data: dict = {"accounts": {}}
    data["accounts"]["cash"] = {
        "display_name": "Cash Account",
        "broker": "manual",
        "capital": float(cash_capital),
        "margin_enabled": bool(cash_margin),
        "margin_multiplier": 2.0,
        "options_level": 3,
        "allowed_actions": [
            "buy_shares", "sell_shares", "sell_csp", "sell_cc",
            "close_csp", "close_cc", "roll_csp", "roll_cc",
            "buy_put", "buy_call", "sell_long_put", "sell_long_call",
        ],
        "max_position_pct": 30,
        "notes": (
            "Standard cash brokerage. With margin off, max share price for a "
            "100-lot is capital/100. With 2x margin on, double that."
        ),
    }
    if has_ira and ira_capital > 0:
        data["accounts"]["roth_ira"] = {
            "display_name": "Roth IRA",
            "broker": "manual",
            "capital": float(ira_capital),
            "margin_enabled": False,
            "margin_multiplier": 1.0,
            "options_level": 2,
            "allowed_actions": [
                "buy_shares", "sell_shares", "sell_csp", "sell_cc",
                "close_csp", "close_cc", "roll_csp", "roll_cc",
            ],
            "max_position_pct": 25,
            "notes": "Tax-advantaged. No margin (IRS). Wheel-only — CSP + CC.",
        }
    return data


def build_watchlist_data(
    tickers: list[str],
    cash_capital: float, cash_margin: bool,
    has_ira: bool, ira_capital: float,
) -> dict:
    return {
        "watchlist": [
            {"symbol": t, "sector": SECTOR_HINTS.get(t, "general"), "notes": ""}
            for t in tickers
        ],
        "scout_sectors": sorted({
            SECTOR_HINTS.get(t, "general") for t in tickers
        } | {"large_cap_tech", "broad_etf"}),
        "scout_filters": {
            "min_avg_volume": 500_000,
            "min_options_open_interest": 100,
            "max_share_price_roth": (
                float(ira_capital) / 100.0 if (has_ira and ira_capital > 0) else 200.0
            ),
            "max_share_price_cash": (
                float(cash_capital) * (2.0 if cash_margin else 1.0) / 100.0
            ),
            "min_iv_rank": 30,
        },
    }


def write_configs(
    config_dir: Path,
    *,
    cash_capital: float,
    cash_margin: bool = False,
    has_ira: bool = False,
    ira_capital: float = 0.0,
    tickers: list[str] | None = None,
    source: str = "firm init",
) -> dict:
    """Write `accounts.yaml` and `watchlist.yaml` into `config_dir`.

    Also ensures `data_store/` and `reports/` exist in the project root
    (config_dir.parent), since the rest of the firm assumes they're present.

    Returns a small summary dict the caller can render to the user.
    """
    if cash_capital <= 0:
        raise ValueError("cash_capital must be a positive USD amount")
    if has_ira and ira_capital <= 0:
        raise ValueError("has_ira=True requires ira_capital > 0")

    raw_tickers = tickers if tickers else list(DEFAULT_TICKERS)
    cleaned = [t.strip().upper() for t in raw_tickers if t and t.strip()]
    if not cleaned:
        cleaned = list(DEFAULT_TICKERS)

    accounts_data = build_accounts_data(
        cash_capital, cash_margin, has_ira, ira_capital,
    )
    watchlist_data = build_watchlist_data(
        cleaned, cash_capital, cash_margin, has_ira, ira_capital,
    )

    config_dir = Path(config_dir)
    config_dir.mkdir(parents=True, exist_ok=True)
    accounts_path = config_dir / "accounts.yaml"
    watchlist_path = config_dir / "watchlist.yaml"
    timestamp = datetime.now().isoformat(timespec="seconds")

    header = (
        f"# Generated by `{source}` on {timestamp}\n"
        "# Edit by hand or re-run setup to regenerate.\n\n"
    )
    accounts_path.write_text(header + yaml.safe_dump(accounts_data, sort_keys=False))
    watchlist_path.write_text(header + yaml.safe_dump(watchlist_data, sort_keys=False))

    root = config_dir.parent
    (root / "data_store").mkdir(exist_ok=True)
    (root / "reports").mkdir(exist_ok=True)

    return {
        "accounts_path": str(accounts_path),
        "watchlist_path": str(watchlist_path),
        "num_accounts": len(accounts_data["accounts"]),
        "num_tickers": len(cleaned),
        "tickers": cleaned,
        "cash_capital": float(cash_capital),
        "cash_margin": bool(cash_margin),
        "has_ira": bool(has_ira),
        "ira_capital": float(ira_capital) if has_ira else 0.0,
    }
